#!/usr/bin/env python3
"""Install managed git hooks for this repository."""

from __future__ import annotations

import argparse
import platform
import shutil
import stat
import subprocess
from pathlib import Path

ROOT = Path(__file__).parent


def resolve_hooks_dir() -> Path:
    result = subprocess.run(
        ["git", "rev-parse", "--git-common-dir"],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode == 0 and result.stdout.strip():
        common_dir = Path(result.stdout.strip())
        if not common_dir.is_absolute():
            common_dir = ROOT / common_dir
        return common_dir / "hooks"
    return ROOT / ".git" / "hooks"


HOOKS_DIR = resolve_hooks_dir()


def _effective_hooks_dir() -> Path:
    result = subprocess.run(
        ["git", "config", "--get", "core.hooksPath"],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode == 0 and result.stdout.strip():
        configured = Path(result.stdout.strip())
        if not configured.is_absolute():
            configured = ROOT / configured
        return configured.resolve()
    return HOOKS_DIR.resolve()


def _ensure_managed_hooks_path(check_only: bool) -> bool:
    desired = HOOKS_DIR.resolve()
    effective = _effective_hooks_dir()
    if effective == desired:
        return True

    if check_only:
        print(f"core.hooksPath points to {effective}; expected {desired}")
        return False

    result = subprocess.run(
        ["git", "config", "--local", "core.hooksPath", str(desired)],
        cwd=ROOT,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError("Failed to configure core.hooksPath for managed hooks")

    print(f"Configured core.hooksPath to {desired}")
    return True


def _refresh_beads_hooks() -> None:
    if not (ROOT / ".beads").exists():
        return

    bd_bin = shutil.which("bd")
    if not bd_bin:
        return

    result = subprocess.run([bd_bin, "hooks", "install"], cwd=ROOT, check=False)
    if result.returncode != 0:
        print("Warning: failed to refresh Beads hooks with 'bd hooks install'.")


PYTHON_DETECT = """\
PYTHON=""
if [ -f ".venv/Scripts/python.exe" ]; then
    PYTHON=".venv/Scripts/python.exe"
elif [ -f ".venv/bin/python" ]; then
    PYTHON=".venv/bin/python"
elif command -v python3 >/dev/null 2>&1; then
    PYTHON="python3"
elif command -v python >/dev/null 2>&1; then
    PYTHON="python"
fi
"""

BEADS_HOOK_DELEGATE = """\
run_beads_hook_file() {
    HOOK_NAME="$1"
    shift

    BEADS_HOOK=".beads/hooks/$HOOK_NAME"
    if [ ! -f "$BEADS_HOOK" ]; then
        return 0
    fi

    sh "$BEADS_HOOK" "$@"
}
"""

PRE_COMMIT = f"""\
#!/usr/bin/env sh
# Generated by install_hooks.py. Do not edit manually.

{PYTHON_DETECT}
{BEADS_HOOK_DELEGATE}

GUARD_EXIT=0
BEADS_EXIT=0

if [ -f "validate.py" ] && [ -d ".venv" ]; then
    if [ -z "$PYTHON" ]; then
        echo "[git-hook] Python not found; skipping quality gate." >&2
    else
        "$PYTHON" validate.py --commit
        GUARD_EXIT=$?
    fi
fi

run_beads_hook_file pre-commit "$@"
BEADS_EXIT=$?

if [ $GUARD_EXIT -ne 0 ]; then
    exit $GUARD_EXIT
fi

exit $BEADS_EXIT
"""

PRE_PUSH = f"""\
#!/usr/bin/env sh
# Generated by install_hooks.py. Do not edit manually.

{PYTHON_DETECT}
{BEADS_HOOK_DELEGATE}

GUARD_EXIT=0
BEADS_EXIT=0

if [ -f "validate.py" ] && [ -d ".venv" ]; then
    if [ -z "$PYTHON" ]; then
        echo "[git-hook] Python not found; skipping quality gate." >&2
    else
        "$PYTHON" validate.py
        GUARD_EXIT=$?
    fi
fi

if command -v bd >/dev/null 2>&1; then
    bd backup export-git || true
fi

run_beads_hook_file pre-push "$@"
BEADS_EXIT=$?

if [ $GUARD_EXIT -ne 0 ]; then
    exit $GUARD_EXIT
fi

exit $BEADS_EXIT
"""

COMMIT_MSG = """\
#!/usr/bin/env sh
# Generated by install_hooks.py. Do not edit manually.

run_beads_hook_file() {
    HOOK_NAME="$1"
    shift

    BEADS_HOOK=".beads/hooks/$HOOK_NAME"
    if [ ! -f "$BEADS_HOOK" ]; then
        return 0
    fi

    sh "$BEADS_HOOK" "$@"
}

GUARD_EXIT=0
BEADS_EXIT=0

COMMIT_MSG_FILE="$1"
if [ -d ".beads" ]; then
    FIRST_LINE=$(grep -v '^#' "$COMMIT_MSG_FILE" | grep -v '^[[:space:]]*$' | head -n1)

    case "$FIRST_LINE" in
        "Merge "*|"Revert "*|"fixup! "*|"squash! "*|"chore(release):"*)
            GUARD_EXIT=0 ;;
        *)
            if echo "$FIRST_LINE" | grep -qE '\\([a-z0-9][a-z0-9-]*-[a-z0-9]+\\)'; then
                GUARD_EXIT=0
            else
                echo "[git-hook] commit-msg: expected '(bd-123)' or '(project-abc)'" >&2
                echo "[git-hook] Example: feat(core): add bootstrap flow (bd-123)" >&2
                GUARD_EXIT=1
            fi
            ;;
    esac
fi

run_beads_hook_file commit-msg "$@"
BEADS_EXIT=$?

if [ $GUARD_EXIT -ne 0 ]; then
    exit $GUARD_EXIT
fi

exit $BEADS_EXIT
"""

POST_MERGE = f"""\
#!/usr/bin/env sh
# Generated by install_hooks.py. Do not edit manually.

{BEADS_HOOK_DELEGATE}
run_beads_hook_file post-merge "$@" || true

if command -v bd >/dev/null 2>&1; then
    bd backup fetch-git || true
fi

{PYTHON_DETECT}
if [ -z "$PYTHON" ]; then
    echo "[git-hook] Python not found; skipping hook refresh." >&2
    exit 0
fi

"$PYTHON" install_hooks.py --force
"""

POST_REWRITE = f"""\
#!/usr/bin/env sh
# Generated by install_hooks.py. Do not edit manually.

{BEADS_HOOK_DELEGATE}
run_beads_hook_file post-rewrite "$@" || true

if command -v bd >/dev/null 2>&1; then
    bd backup fetch-git || true
fi

{PYTHON_DETECT}
if [ -z "$PYTHON" ]; then
    echo "[git-hook] Python not found; skipping hook refresh." >&2
    exit 0
fi

"$PYTHON" install_hooks.py --force
"""

HOOKS = {
    "pre-commit": PRE_COMMIT,
    "pre-push": PRE_PUSH,
    "commit-msg": COMMIT_MSG,
    "post-merge": POST_MERGE,
    "post-rewrite": POST_REWRITE,
}


def make_executable(path: Path) -> None:
    if platform.system() != "Windows":
        mode = path.stat().st_mode
        path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def differs(path: Path, expected: str) -> bool:
    if not path.exists():
        return True
    return path.read_text(encoding="utf-8") != expected


def install(check_only: bool, force: bool) -> int:
    if not check_only:
        _refresh_beads_hooks()

    path_ok = _ensure_managed_hooks_path(check_only=check_only)
    if not path_ok and check_only:
        return 1

    if not HOOKS_DIR.exists():
        if check_only:
            print(f"Hooks directory not found: {HOOKS_DIR}")
            return 1
        HOOKS_DIR.mkdir(parents=True, exist_ok=True)

    pending = [name for name, content in HOOKS.items() if differs(HOOKS_DIR / name, content)]
    if not pending:
        print("All hooks are up to date.")
        return 0

    if check_only:
        print("Hooks needing updates:")
        for name in pending:
            print(f"  - {name}")
        return 1

    for name in pending:
        path = HOOKS_DIR / name
        if path.exists() and not force:
            existing = path.read_text(encoding="utf-8")
            if "Generated by install_hooks.py" not in existing:
                response = (
                    input(f"Hook '{name}' has custom content. Overwrite? [y/N]: ").strip().lower()
                )
                if response not in {"y", "yes"}:
                    print(f"Skipped {name}")
                    continue

        path.write_text(HOOKS[name], encoding="utf-8", newline="\n")
        make_executable(path)
        print(f"Installed hook: {path}")

    print("Hook installation complete.")
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Install managed git hooks")
    parser.add_argument("--check", action="store_true", help="Check whether hooks are up to date")
    parser.add_argument(
        "--force", action="store_true", help="Overwrite existing hooks without prompting"
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    return install(check_only=args.check, force=args.force)


if __name__ == "__main__":
    raise SystemExit(main())
