#!/usr/bin/env python3
"""Install managed git hooks for this repository."""

from __future__ import annotations

import argparse
import platform
import stat
import subprocess
from pathlib import Path

ROOT = Path(__file__).parent


def resolve_hooks_dir() -> Path:
    result = subprocess.run(
        ["git", "rev-parse", "--git-path", "hooks"],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode == 0 and result.stdout.strip():
        return Path(result.stdout.strip())
    return ROOT / ".git" / "hooks"


HOOKS_DIR = resolve_hooks_dir()

PYTHON_DETECT = """\
if [ -f ".venv/Scripts/python.exe" ]; then
    PYTHON=".venv/Scripts/python.exe"
elif [ -f ".venv/bin/python" ]; then
    PYTHON=".venv/bin/python"
elif command -v python3 >/dev/null 2>&1; then
    PYTHON="python3"
elif command -v python >/dev/null 2>&1; then
    PYTHON="python"
else
    echo "[git-hook] Python not found; skipping quality gate." >&2
    exit 0
fi
"""

PRE_COMMIT = f"""\
#!/usr/bin/env sh
# Generated by install_hooks.py. Do not edit manually.

{PYTHON_DETECT}

if [ ! -f "validate.py" ] || [ ! -d ".venv" ]; then
    exit 0
fi

"$PYTHON" validate.py --commit
exit $?
"""

PRE_PUSH = f"""\
#!/usr/bin/env sh
# Generated by install_hooks.py. Do not edit manually.

{PYTHON_DETECT}

if [ ! -f "validate.py" ] || [ ! -d ".venv" ]; then
    exit 0
fi

if command -v bd >/dev/null 2>&1; then
    bd backup export-git || true
fi

"$PYTHON" validate.py
exit $?
"""

COMMIT_MSG = """\
#!/usr/bin/env sh
# Generated by install_hooks.py. Do not edit manually.

# Skip bead id enforcement if beads is not initialized in this repo.
if [ ! -d ".beads" ]; then
    exit 0
fi

COMMIT_MSG_FILE="$1"
FIRST_LINE=$(grep -v '^#' "$COMMIT_MSG_FILE" | grep -v '^[[:space:]]*$' | head -n1)

case "$FIRST_LINE" in
    "Merge "*|"Revert "*|"fixup! "*|"squash! "*|"chore(release):"*)
        exit 0 ;;
esac

if echo "$FIRST_LINE" | grep -qE '\\([a-z0-9][a-z0-9-]*-[a-z0-9]+\\)'; then
    exit 0
fi

echo "[git-hook] commit-msg: missing bead id trailer, expected '(bd-123)' or '(project-abc)'" >&2
echo "[git-hook] Example: feat(core): add bootstrap flow (bd-123)" >&2
exit 1
"""

POST_MERGE = f"""\
#!/usr/bin/env sh
# Generated by install_hooks.py. Do not edit manually.

if command -v bd >/dev/null 2>&1; then
    bd backup fetch-git || true
fi

{PYTHON_DETECT}
"$PYTHON" install_hooks.py --force
"""

POST_REWRITE = f"""\
#!/usr/bin/env sh
# Generated by install_hooks.py. Do not edit manually.

if command -v bd >/dev/null 2>&1; then
    bd backup fetch-git || true
fi

{PYTHON_DETECT}
"$PYTHON" install_hooks.py --force
"""

HOOKS = {
    "pre-commit": PRE_COMMIT,
    "pre-push": PRE_PUSH,
    "commit-msg": COMMIT_MSG,
    "post-merge": POST_MERGE,
    "post-rewrite": POST_REWRITE,
}


def make_executable(path: Path) -> None:
    if platform.system() != "Windows":
        mode = path.stat().st_mode
        path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def differs(path: Path, expected: str) -> bool:
    if not path.exists():
        return True
    return path.read_text(encoding="utf-8") != expected


def install(check_only: bool, force: bool) -> int:
    if not HOOKS_DIR.exists():
        print(f"Hooks directory not found: {HOOKS_DIR}")
        return 1

    pending = [name for name, content in HOOKS.items() if differs(HOOKS_DIR / name, content)]
    if not pending:
        print("All hooks are up to date.")
        return 0

    if check_only:
        print("Hooks needing updates:")
        for name in pending:
            print(f"  - {name}")
        return 1

    for name in pending:
        path = HOOKS_DIR / name
        if path.exists() and not force:
            existing = path.read_text(encoding="utf-8")
            if "Generated by install_hooks.py" not in existing:
                response = (
                    input(f"Hook '{name}' has custom content. Overwrite? [y/N]: ").strip().lower()
                )
                if response not in {"y", "yes"}:
                    print(f"Skipped {name}")
                    continue

        path.write_text(HOOKS[name], encoding="utf-8", newline="\n")
        make_executable(path)
        print(f"Installed hook: {path}")

    print("Hook installation complete.")
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Install managed git hooks")
    parser.add_argument("--check", action="store_true", help="Check whether hooks are up to date")
    parser.add_argument(
        "--force", action="store_true", help="Overwrite existing hooks without prompting"
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    return install(check_only=args.check, force=args.force)


if __name__ == "__main__":
    raise SystemExit(main())
